import { notFound } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { requireAgency } from "@/lib/auth";
import TaskFilterBar from "@/components/TaskFilterBar";
import NewTaskButton from "@/components/NewTaskButton";
import SortableTaskList from "@/components/SortableTaskList";
import { isTaskStale, type TaskRow } from "@/lib/tasks";
import { Sparkles, ArrowLeft } from "lucide-react";

export const dynamic = "force-dynamic";

interface SearchParams { status?: string; group?: string; owner?: string }

export default async function ClientTasksPage({
 params, searchParams,
}: {
 params: Promise<{ id: string }>;
 searchParams: Promise<SearchParams>;
}) {
 const { id } = await params;
 const sp = await searchParams;
 const session = await requireAgency();
 const supabase = await createClient();

 const isSuperAdmin = session.role === "super_admin";
 const clientQ = supabase.from("clients").select("id, name, brand_name").eq("id", id);
 const { data: client } = await (isSuperAdmin ? clientQ : clientQ.eq("agency_id", session.agencyId)).single();
 if (!client) notFound();

 const tasksQ = supabase
 .from("tasks")
 .select("*, tracked_keywords(id, keyword)")
 .eq("client_id", id)
 .order("status", { ascending: true })
 .order("priority", { ascending: true })
 .order("created_at", { ascending: false })
 .limit(300);
 const { data: rawTasks } = await (isSuperAdmin ? tasksQ : tasksQ.eq("agency_id", session.agencyId));

 type Joined = TaskRow & {
 tracked_keywords: { id: string; keyword: string } | { id: string; keyword: string }[] | null;
 };
 const tasks = (rawTasks ?? []) as Joined[];

 const keywordIds = Array.from(new Set(tasks.map((t) => t.tracked_keyword_id).filter(Boolean) as string[]));
 type Sig = { rankPosition: number | null; gapLabel: string; aioPresent: boolean | null; clientCited: boolean | null; citedDomainCount: number };
 const latestByKw = new Map<string, Sig>();
 if (keywordIds.length > 0) {
 const { data: rows } = await supabase
 .from("search_results")
 .select("tracked_keyword_id, rank_position, aio_present, client_cited, cited_domains, gap_label, created_at")
 .in("tracked_keyword_id", keywordIds)
 .order("created_at", { ascending: false });
 for (const r of rows ?? []) {
 const k = r.tracked_keyword_id as string;
 if (latestByKw.has(k)) continue;
 latestByKw.set(k, {
 rankPosition: r.rank_position as number | null,
 gapLabel: r.gap_label as string,
 aioPresent: r.aio_present as boolean | null,
 clientCited: r.client_cited as boolean | null,
 citedDomainCount: ((r.cited_domains as string[] | null) ?? []).length,
 });
 }
 }
 function staleFor(task: Joined): boolean {
 if (!task.tracked_keyword_id) return false;
 const cur = latestByKw.get(task.tracked_keyword_id);
 if (!cur) return false;
 return isTaskStale(task.context_snapshot, cur);
 }

 const counts = {
 all: tasks.length,
 todo: tasks.filter((t) => t.status === "todo").length,
 in_progress: tasks.filter((t) => t.status === "in_progress").length,
 done: tasks.filter((t) => t.status === "done").length,
 };

 const statusFilter = sp.status ?? "open";
 const filtered = tasks.filter((t) => {
 if (statusFilter === "open" && (t.status === "done" || t.status === "skipped")) return false;
 if (statusFilter !== "open" && statusFilter !== "all" && t.status !== statusFilter) return false;
 if (sp.group && t.group_name !== sp.group) return false;
 if (sp.owner && t.owner !== sp.owner) return false;
 return true;
 });

 // Group by keyword
 const byKeyword = new Map<string, { label: string; href: string | null; rows: Joined[] }>();
 const NO_KW = "__no_keyword__";
 for (const t of filtered) {
 const kw = Array.isArray(t.tracked_keywords) ? t.tracked_keywords[0] : t.tracked_keywords;
 const key = kw?.id ?? NO_KW;
 const label = kw?.keyword ?? "Client-wide execution tasks";
 const href = kw ? `/dashboard/clients/${id}/keywords/${kw.id}` : null;
 const arr = byKeyword.get(key) ?? { label, href, rows: [] };
 arr.rows.push(t);
 byKeyword.set(key, arr);
 }

 return (
 <div className="p-4 sm:p-8 max-w-6xl mx-auto space-y-6">
 <div className="border-b border-white/[0.05] pb-6">
 <div className="flex items-center gap-2 mb-1.5 text-xs font-mono text-gray-500">
 <Link href={`/dashboard/clients/${id}`} className="hover:text-amber-400 transition-colors flex items-center gap-1">
 <ArrowLeft size={13} />
 <span>{client.brand_name ?? client.name}</span>
 </Link>
 <span className="text-gray-600">/</span>
 <span className="text-white font-bold">Execution Tickets</span>
 </div>
 <div className="flex items-center justify-between gap-4 flex-wrap">
 <div>
 <h1 className="text-2xl font-heading font-black text-white tracking-tight">Client Task Pipeline</h1>
 <p className="text-xs font-mono text-gray-400 mt-0.5">
 Actionable SEO & GEO optimization tasks generated by AI citation briefs or created manually.
 </p>
 </div>
 <NewTaskButton clientId={id} />
 </div>
 </div>

 <div className="bg-[#121215] border border-white/[0.08] p-4 rounded-[20px] shadow-xl">
 <TaskFilterBar
 counts={counts}
 groups={[
 { value: "Content", label: "Content" },
 { value: "Technical", label: "Technical" },
 { value: "Off-page", label: "Off-page" },
 ]}
 owners={[
 { value: "Writer", label: "Writer" },
 { value: "Developer", label: "Developer" },
 { value: "SEO", label: "SEO" },
 { value: "Outreach", label: "Outreach" },
 ]}
 />
 </div>

 {filtered.length === 0 ? (
 <div className="rounded-[20px] border border-dashed border-white/15 bg-[#121215] p-16 text-center shadow-2xl">
 <Sparkles size={36} className="text-amber-500 mx-auto mb-4 animate-bounce" />
 <p className="text-lg font-heading font-bold text-white mb-1">
 {tasks.length === 0 ? "No Tasks Created Yet" : "No Tasks Match Current Filters"}
 </p>
 <p className="text-xs text-gray-400 max-w-md mx-auto">
 {tasks.length === 0
 ? "Generate AI battle briefs on your keywords tab or create tickets above to track client progress."
 : "Try clearing your owner, status, or group filters above."}
 </p>
 </div>
 ) : (
 <div className="space-y-6">
 {Array.from(byKeyword.entries()).map(([key, group]) => (
 <div key={key} className="bg-[#121215] border border-white/[0.08] rounded-[20px] p-6 shadow-2xl space-y-4">
 <div className="flex items-center justify-between border-b border-white/[0.05] pb-3">
 <h2 className="text-sm font-heading font-bold text-white">
 {group.href ? (
 <Link href={group.href} className="hover:text-amber-400 transition-colors flex items-center gap-2">
 <span className="w-2 h-2 rounded-full bg-amber-500" />
 <span>&ldquo;{group.label}&rdquo;</span>
 </Link>
 ) : (
 <span className="flex items-center gap-2">
 <span className="w-2 h-2 rounded-full bg-cyan-500" />
 <span>{group.label}</span>
 </span>
 )}
 </h2>
 <span className="rounded-full bg-card/5 border border-white/10 px-2.5 py-0.5 text-[11px] font-mono font-bold text-gray-400">
 {group.rows.length} {group.rows.length === 1 ? "ticket" : "tickets"}
 </span>
 </div>
 <SortableTaskList
 rows={group.rows.map((t) => ({
 task: t as TaskRow,
 keywordLabel: null,
 keywordHref: null,
 isStale: staleFor(t),
 }))}
 />
 </div>
 ))}
 </div>
 )}
 </div>
 );
}
